### ISSUE TITLE
"Model_selection" Rmd: standardize the variables for ridge and lasso

### ISSUE THREAD

**Issue by aminrahimian** [aminrahimian/data-for-good#18]
If the variables are not standardizes or on the same unit, variables that vary on a smaller scale will be penalized for their scale

**Comment by Erin-ONeill** [comment]
The variables should be standardized by default. The textbook states "Note that by default, the glmnet() function standardizes the variables so that they are on the same scale. To turn off this default setting, use the argument standardize = FALSE." We did not include 'standardize = FALSE', so by default the variables should be standardized. I can add a note to the tutorial to address that this is happening though.
